services:
  - type: web
    name: plant-saathi-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_D0wZTJ7uqdRr@ep-damp-pine-a83kg2ln-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: GOOGLE_GEMINI_API_KEY
        value: AIzaSyCIBfxO0ucbAZXYE73P-vvTQFcCjn52y8w
      - key: JWT_SECRET
        sync: false
      - key: CRON_SECRET
        generateValue: true
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: FRONTEND_URL
        value: https://apinew4aug-18met8g4f-ranchopandas-projects.vercel.app/
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: free

databases:
  - name: plant-saathi-db
    databaseName: plant_saathi
    user: plant_saathi_user
    plan: free
